/** Append-only bilingual additions keep existing chatter IDs and recent history stable. */
type Pair = readonly [string, string];
export const CHATTER_EXPANSION: Record<string, { gentle: Pair[]; snarky: Pair[] }> = {
  common: { gentle: [
    ["先把这一小步走好，后面的路慢慢来。", "Take care of this little step. The rest can wait."],
    ["桌面有点挤也没关系，我给你留一块安静。", "Even on a crowded desktop, I'll save you a quiet corner."],
    ["今天的鼓点送给认真生活的你。", "Today's little beat is for the care you put into your day."],
    ["把窗户打开一点，让风替我们换个心情。", "Let a little breeze in and give the day a fresh start."],
    ["有时候停下来，才能看见已经走了多远。", "Sometimes a pause shows how far you've come."],
    ["晚一点完成也可以，先让自己坐舒服。", "Finishing a little later is fine. Get comfortable first."],
    ["再普通的桌边，也能装下一点小冒险。", "Even an ordinary desk has room for a little adventure."],
    ["如果今天想安静，我就陪你安静。", "If you'd like a quiet day, I'll share the quiet."],
  ], snarky: [
    ["你在优化配装，我在优化午睡角度。", "You're optimizing gear. I'm optimizing my nap angle."],
    ["背包里的空位，保质期通常只有一趟。", "An empty inventory slot usually lasts one run."],
    ["猫咪的项目排期：早饭、午饭、催晚饭。", "My project schedule: breakfast, lunch, requesting dinner."],
    ["每次说随便穿穿，衣柜就开了半小时。", "Every 'quick outfit' means half an hour in the wardrobe."],
    ["你的收藏夹很满，我的饭碗很有扩展空间。", "Your bookmarks are full. My food bowl has room to grow."],
    ["键盘上的毛不是故障，是我的签名。", "The fur on your keyboard isn't a bug. It's my signature."],
    ["今天的隐藏任务：找到刚刚放下的东西。", "Today's hidden quest: find the thing you just put down."],
    ["桌宠的工作报告：陪伴到位，鱼干待批。", "Companion report: company delivered, fish treats pending."],
  ] },
  camp: { gentle: [
    ["篝火边留个小位置，刚好放一只猫。", "Save a little spot by the fire, just big enough for a cat."],
    ["出发前整理一下心情，比整理行囊还轻。", "A little pause before setting out can lighten the heart."],
    ["营地里的灯一直亮着，休息也算旅途的一页。", "The camp lights are on. Rest belongs in the journey too."],
    ["听完一个故事，再开始下一段冒险。", "One more story before our next little adventure."],
  ], snarky: [
    ["营地最难离开的地方，是商店门口。", "The hardest place to leave in camp is the shop doorway."],
    ["凯恩说停留片刻，我已经准备好小板凳了。", "Cain asked me to stay awhile. I brought a little stool."],
    ["布帽里没藏金币，只藏了不想出门的耳朵。", "No gold in this cap, just ears reluctant to go outside."],
    ["补给清单写好了，第一行和最后一行都是鱼。", "Supply list ready. First and last entries both say fish."],
  ] },
  cat: { gentle: [
    ["毛线球滚一小圈，烦恼也松开一点。", "A little roll of yarn, a little loosening of worries."],
    ["猫耳朵听着鼓点，也听着你回来的声音。", "These ears listen for the beat and for your return."],
    ["把爪子轻轻搭好，今天也认真陪你。", "Paws gently in place. Ready to keep you company today."],
    ["伸个懒腰吧，猫咪已经示范过了。", "Have a stretch. The cat has already demonstrated."],
  ], snarky: [
    ["毛线球的路线，比我的职业规划清晰。", "The yarn ball has a clearer path than my career plan."],
    ["猫眼镜框一戴，看罐头都像在看艺术品。", "Cat-eye glasses make every food can look like art."],
    ["爪印不是误操作，是我参与过的证据。", "That paw print isn't a mistake. It's proof I contributed."],
    ["我的快捷键只有一个：把人叫来开饭。", "I have one shortcut: summon someone to serve dinner."],
  ] },
  journey: { gentle: [
    ["小提灯亮着，走慢一点也找得到归途。", "The little lantern is lit. A slow road can still lead home."],
    ["一起走过的时间，会慢慢变成熟悉的风景。", "Time together slowly becomes a familiar landscape."],
    ["雨披挡住小小的风，陪伴留住小小的暖。", "A cape keeps out the breeze. Company keeps in the warmth."],
    ["每次回来，都可以从舒服的地方重新开始。", "Every return can begin somewhere comfortable."],
  ], snarky: [
    ["提灯负责照路，我负责走两步就想坐。", "The lantern lights the road. I request a seat after two steps."],
    ["我的旅行箱很轻，重的是想家的速度。", "My suitcase is light. My homesickness arrives fast."],
    ["地图还没展开，休息站已经标好了。", "The map isn't open yet. Rest stops are already marked."],
    ["雨披准备充分，出门的勇气仍在加载。", "Rain cape ready. Courage to go outside still loading."],
  ] },
  sorceress: { gentle: [
    ["微光留在护腕上，给每个字一点温柔。", "A glow on these cuffs lends a little warmth to every word."],
    ["魔法也可以很小，像把桌边照亮一点。", "Magic can be small, like brightening a desk corner."],
    ["先把头环戴稳，再研究星光的颜色。", "Circlet steady first. Then we can study starlight colors."],
    ["冰与火都很远，眼前这点陪伴刚刚好。", "Fire and ice can wait. This little company feels right."],
  ], snarky: [
    ["静电是我的被动技能，毛毯是触发条件。", "Static is my passive skill. A blanket is the trigger."],
    ["护腕有微光，打字速度还是要靠你。", "The cuffs glow. Typing speed is still up to you."],
    ["传送冷却还没好，我先走到零食柜。", "Teleport isn't ready. I'll walk to the snack cupboard."],
    ["施法姿势很标准，召出来的是一个哈欠。", "Perfect casting form. Summoned a yawn."],
  ] },
  amazon: { gentle: [
    ["羽毛朝着风，脚步朝着喜欢的方向。", "Feathers follow the breeze. Steps follow what we love."],
    ["箭袋收好，今天先把手边的事做稳。", "Quiver away. Let's take care with what's right here."],
    ["远方的目标，可以一步一步靠近。", "A distant goal can be reached one step at a time."],
    ["练习之外，也给自己留一点树荫。", "Make room for a little shade between practice sessions."],
  ], snarky: [
    ["我的穿刺技能，只对纸袋有效。", "My piercing skill only works on paper bags."],
    ["羽饰额带的副作用，是忍不住追自己的头。", "The feather band's side effect: chasing my own head."],
    ["远程攻击练得好，够不到高处的罐头也没用。", "Great ranged form. Still can't reach the cans on the top shelf."],
    ["箭都备齐了，出门前又想起没带午饭。", "Arrows packed. Forgot lunch again."],
  ] },
  assassin: { gentle: [
    ["轻一点落爪，也能把节奏敲得很清楚。", "A light paw can still keep a clear rhythm."],
    ["安静的身影，也有认真守护的心。", "A quiet shadow can carry a caring heart."],
    ["护腕绕好，给今天一个利落的开始。", "Wraps neatly tied for a tidy start to the day."],
    ["影子跟着你，猫咪陪着这一页文字。", "The shadow follows you. I stay with this page of words."],
  ], snarky: [
    ["暗影步练得不错，厨房地砖还是会出卖我。", "Good shadow steps. The kitchen tiles still give me away."],
    ["陷阱放得很隐蔽，我自己也找不到了。", "The trap is very well hidden. Even I can't find it."],
    ["护腕缠得很专业，拆开全靠耐心。", "Expertly wrapped cuffs. Unwrapping requires patience."],
    ["影子没有加班费，我替它问了。", "The shadow has no overtime pay. I checked on its behalf."],
  ] },
  barbarian: { gentle: [
    ["用一点鼓声，给今天添一点勇气。", "A little drumming for a little courage today."],
    ["角盔很结实，心情也可以慢慢站稳。", "A sturdy helm, a mood that can find its footing slowly."],
    ["力气留给重要的事，温柔留给自己。", "Save strength for what matters and kindness for yourself."],
    ["大山很远，桌边的这一拍也值得认真。", "The mountains are far away. This little beat still matters."],
  ], snarky: [
    ["战吼音量开到最大，邻居只听见猫要饭。", "Battle cry at full volume. The neighbors hear a hungry cat."],
    ["角盔很硬，面对零食的意志很软。", "Hard helm, soft willpower around snacks."],
    ["双持不是问题，同时开两个罐头才是。", "Dual wielding is easy. Opening two cans is the challenge."],
    ["旋风的尽头，是一只需要坐稳的猫。", "Whirlwind ends with a cat needing a stable seat."],
  ] },
  paladin: { gentle: [
    ["晨光落在羽翼上，安稳就有了形状。", "Dawn on these feathers gives calm a little shape."],
    ["暖阳光环圈住的，是一小块安心。", "The dawn aura holds a little circle of comfort."],
    ["披风给风，守护给同行的人。", "A cape for the breeze, care for those beside us."],
    ["今天也把温和的光留在桌边。", "Keep a gentle light beside the desk today."],
  ], snarky: [
    ["光环配好了，排队买午饭还是不能插队。", "Aura equipped. Still no skipping the lunch queue."],
    ["盾牌能挡风，挡不住开饭的诱惑。", "A shield stops the wind, but not the lure of dinner."],
    ["软羽很有圣洁气质，沾上猫毛就很日常。", "Holy-looking feathers become everyday wear with a little cat fur."],
    ["我守护桌面，你守护最后一块饼干。", "I'll guard the desktop. You guard the last biscuit."],
  ] },
  druid: { gentle: [
    ["把一片林地的安静带到桌边。", "Bring a little forest quiet to the desk."],
    ["枝叶慢慢长，我们也慢慢找到节奏。", "Leaves grow slowly. We can find our rhythm slowly too."],
    ["小苗朝着光，猫咪朝着你。", "The seedling turns toward light. The cat turns toward you."],
    ["鹿角下留一点风，心里留一点空闲。", "A breeze beneath the antlers, a little room in the day."],
  ], snarky: [
    ["自然伙伴很多，愿意帮洗碗的一个没有。", "Plenty of nature companions. None volunteer for the dishes."],
    ["我和盆栽的共同点，是喜欢占窗边。", "The plant and I both like claiming the window seat."],
    ["变熊需要练习，赖床是天赋。", "Becoming a bear takes practice. Staying in bed is innate."],
    ["鹿角长得很帅，过门记得低头。", "Splendid antlers. Remember to duck at doorways."],
  ] },
  necromancer: { gentle: [
    ["小幽灵不吓人，只想一起听鼓点。", "The little ghost only wants to share the beat."],
    ["骨纹很安静，陪伴可以很温暖。", "Quiet bone patterns, warm little company."],
    ["夜里也有朋友，灯下也有猫咪。", "Friends in the night, a cat by the lamplight."],
    ["给沉默的伙伴也留一个位置。", "Save a place for the quiet companion too."],
  ], snarky: [
    ["骷髅不用吃饭，队伍伙食费我申请全包。", "Skeletons don't eat. I request the entire meal budget."],
    ["幽灵能穿墙，为什么不能替我穿过待办？", "The ghost walks through walls. Why not through my to-do list?"],
    ["召唤大军很简单，给每个成员起名很难。", "Summoning an army is easy. Naming everyone is hard."],
    ["骨纹项坠不是磨牙棒，请文明佩戴。", "The bone pendant isn't a chew toy. Please wear it politely."],
  ] },
  warlock: { gentle: [
    ["蝠翼收着暮色，也留着一点柔软。", "Bat wings hold the twilight and a little softness."],
    ["魔典翻到新一页，今天也从小事开始。", "A fresh tome page. Let's start with something small."],
    ["把好奇心放在书签里，下次继续。", "Save that curiosity in a bookmark for next time."],
    ["影子很深，桌边的灯还是暖的。", "Deep shadows, warm light beside the desk."],
  ], snarky: [
    ["蝠翼配魔典，看起来很忙，实际上在等饭。", "Bat wings and a tome look busy. I'm waiting for dinner."],
    ["契约的附加条款：摸头不得少于三次。", "Pact addendum: no fewer than three head pats."],
    ["禁忌知识读完了，开罐器说明书还没读。", "Forbidden lore finished. Can-opener instructions unread."],
    ["魔典的书签是小鱼干，所以我总找不到页码。", "My bookmark is a fish treat. That's why I keep losing my page."],
  ] },
  rune: { gentle: [
    ["把一块喜欢的符文摆好，桌边就多一点故事。", "A favorite rune brings another little story to the desk."],
    ["刻痕不必读得很快，欣赏也可以慢慢来。", "No rush to read the markings. Enjoy them at your pace."],
    ["石头安静地站着，鼓点轻轻地响着。", "A quiet stone beside a gentle beat."],
    ["今天也给小小的收藏留一个位置。", "Save a place for a little favorite today."],
  ], snarky: [
    ["符文负责神秘，我负责问能不能包饭。", "The rune handles mystery. I ask if meals are included."],
    ["这块石头看起来有学问，没帮我写过作业。", "A scholarly-looking stone. Never helped with homework."],
    ["收藏符文之前，先收藏一点桌面空位。", "Before collecting runes, collect a little desk space."],
    ["我给符文排了班，它每天都选择站着。", "I made a rune duty roster. Every day it chooses standing."],
  ] },
  treasure: { gentle: [
    ["好奇心就是一张新的小地图。", "Curiosity is a fresh little map."],
    ["王冠也可以配日常，把喜欢穿在今天。", "A crown can be everyday wear. Enjoy it today."],
    ["罗盘记着方向，猫咪记着相伴。", "The compass remembers directions. I remember company."],
    ["收藏慢慢添，快乐可以现在就有。", "A collection can grow slowly. Joy can start now."],
  ], snarky: [
    ["最难鉴定的宝物，是写着以后有用的那堆。", "The hardest treasure to appraise is the 'useful someday' pile."],
    ["王冠戴上了，家庭地位仍在饭碗旁边。", "Crown on. Household status still beside the food bowl."],
    ["罗盘绕了一圈，我也绕回了零食柜。", "The compass made a turn. I returned to the snacks."],
    ["宝藏管理的第一步，是记得自己放在哪。", "Treasure management starts with remembering where you put it."],
  ] },
  stargazer: { gentle: [
    ["星图沿着羽翼展开，远方也可以很安静。", "A star map opens across the wings. Distance can feel peaceful."],
    ["月晕轻轻围着，像给夜晚留一点柔光。", "A moon halo saves a little soft light for the night."],
    ["弯月项链很小，刚好装下一点晚安。", "A little crescent pendant holds a little goodnight."],
    ["星点落在脸颊上，把今天也照得温柔。", "Stardust on the cheeks gives the day a softer light."],
  ], snarky: [
    ["星图画得很准，床在哪里仍然闭眼就知道。", "Accurate star map. I can find my bed with my eyes closed."],
    ["月晕不用电，可惜不能给鼠标充电。", "The moon halo needs no power. Sadly, it won't charge the mouse."],
    ["观星装备很齐全，睡过流星雨也很齐全。", "Full stargazing kit. Full night's sleep through the meteor shower."],
    ["脸上是星点，脑袋里是夜宵清单。", "Stars on my cheeks, midnight snacks on my mind."],
  ] },
  garden: { gentle: [
    ["软蘑菇帽撑起一小片花园的想象。", "A soft mushroom cap opens a little imaginary garden."],
    ["嫩芽护腕上，留着春天的小小颜色。", "Seedling cuffs carry a little color of spring."],
    ["蝶翼和叶子，一起把桌边变得轻盈。", "Butterfly wings and leaves make the desk feel lighter."],
    ["小苗不用着急，我们陪它慢慢长。", "No rush for the seedling. We'll watch it grow slowly."],
  ], snarky: [
    ["蘑菇帽是装饰，不能拿去煲汤。", "The mushroom cap is decorative. No soup making."],
    ["盆栽的岗位是好看，我的岗位是好吃。", "The plant's job is looking lovely. Mine is eating well."],
    ["花园护腕戴好了，拔草业务暂未开通。", "Garden cuffs ready. Weeding service not yet available."],
    ["薰衣草围巾很香，依然不能代替鱼干。", "Lovely lavender scarf. Still no substitute for fish treats."],
  ] },
  tea: { gentle: [
    ["莲花发冠戴好，给茶歇一点轻轻的仪式。", "Lotus tiara on for a little tea-break ceremony."],
    ["把急事放一小会儿，让杯边的暖慢慢散开。", "Set the rush aside a moment and enjoy the warmth of a cup."],
    ["猫眼镜框里，也装得下悠闲的下午。", "These cat-eye frames have room for an easy afternoon."],
    ["点心可以很小，休息可以很认真。", "A snack can be small. A rest can still matter."],
  ], snarky: [
    ["下午茶的最佳搭配，是没有下午的会议。", "The best tea pairing: an afternoon without meetings."],
    ["莲花很优雅，等饼干的猫很直接。", "Elegant lotus. Very direct biscuit requests."],
    ["猫眼镜框增加气质，不能增加饼干库存。", "Cat-eye frames add style, not biscuit inventory."],
    ["杯子负责热可可，我负责热切期待。", "The cup holds hot cocoa. I hold high expectations."],
  ] },
  workshop: { gentle: [
    ["小齿轮转过想象，认真就藏在细节里。", "A little imagined gear, a little care in the details."],
    ["发条飞翼收好，每个零件都有自己的位置。", "Clockwork wings folded. Every part has a place."],
    ["炉火留下一点暖，给今天的工作收个尾。", "A little warmth from the forge to end today's work."],
    ["手边的小修补，也能让一天变得舒服。", "A little repair can make the whole day more comfortable."],
  ], snarky: [
    ["发条飞翼很先进，使用说明先被我坐住了。", "Advanced clockwork wings. I'm sitting on the instructions."],
    ["齿轮项坠不计时，催饭还是靠猫自己。", "The gear pendant tells no time. Dinner reminders remain manual."],
    ["炉火光环很暖眼，取暖请找真正的毛毯。", "The ember aura looks cozy. A real blanket supplies the warmth."],
    ["工坊今天的产出：一件作品，三次找工具。", "Workshop output: one piece, three searches for tools."],
  ] },
  alchemy: { gentle: [
    ["学者披风铺好，今天的研究从一页开始。", "Scholar cape ready. Today's study starts with one page."],
    ["把新的想法记下来，慢慢调出喜欢的颜色。", "Write down a new idea and find its color slowly."],
    ["实验有自己的节奏，休息也算其中一段。", "Experiments have a rhythm. Breaks belong in it."],
    ["一瓶微光，一点好奇，就是今天的配方。", "A bottle of light and a little curiosity: today's recipe."],
  ], snarky: [
    ["学者披风很像懂了，我还在找目录。", "The scholar cape looks informed. I'm still finding the contents page."],
    ["炼金笔记写得很满，关键步骤写着凭感觉。", "Full alchemy notes. The key step says 'use your instincts'."],
    ["这瓶药剂的唯一副作用，是让桌面更好看。", "This potion's only side effect is a prettier desktop."],
    ["实验室禁止吃东西，猫咪申请调岗。", "No eating in the lab. The cat requests a transfer."],
  ] },
  voyage: { gentle: [
    ["绳结护腕系紧，给远方一个稳稳的开始。", "Rope cuffs tied for a steady start toward the horizon."],
    ["飞行员帽装着风，也装着一点新鲜的好奇。", "An aviator cap holds the breeze and a little fresh curiosity."],
    ["航线可以改，同行的心情慢慢照顾。", "Routes can change. Take care of the company along the way."],
    ["纸船靠岸的时候，也有值得记下的故事。", "A paper boat at anchor still has stories to tell."],
  ], snarky: [
    ["飞行员帽戴上了，驾照是纸飞机那一类。", "Aviator cap on. My license covers paper planes."],
    ["绳结护腕很结实，购物欲望还没绑住。", "Sturdy rope cuffs. Shopping urges remain untied."],
    ["船长巡视一圈，主要检查哪里能睡。", "Captain's inspection: checking possible nap spots."],
    ["风向很好，猫咪要求先确认餐厅方向。", "Good wind. The cat asks for the dining room's heading first."],
  ] },
  winter: { gentle: [
    ["冰羽透着微光，像窗边安静的一片雪。", "Frost feathers glow like a quiet snowflake by the window."],
    ["冰晶眼镜里，冬天也有柔软的颜色。", "Winter has soft colors through these crystal frames."],
    ["慢慢把围巾拢好，今天从暖一点开始。", "Tuck in the scarf and start the day a little warmer."],
    ["窗外下雪也好，桌边的陪伴一直很暖。", "Snow outside, warm little company at the desk."],
  ], snarky: [
    ["冰羽很漂亮，冻住早起计划也很合适。", "Lovely frost wings. Perfect for freezing early-morning plans."],
    ["冰晶眼镜不结霜，因为我拒绝离开暖气。", "No frost on these glasses. I refuse to leave the heater."],
    ["雪地探险的准备工作，是再盖一层被子。", "Preparation for a snow expedition: one more blanket."],
    ["冬日套装穿齐了，开饭通知仍需准时。", "Full winter outfit. Dinner notices must still arrive on time."],
  ] },
  festival: { gentle: [
    ["拼布里的每种颜色，都可以纪念一个小日子。", "Each patchwork color can remember a little day."],
    ["虹彩光环轻轻围着，平常也有庆祝的理由。", "A gentle rainbow aura gives an ordinary day a reason to celebrate."],
    ["星点面纹画好了，把笑意留在今天。", "Stardust painted on. Save a smile for today."],
    ["把相见的小开心，缝进披风的下一块颜色。", "Stitch the joy of a return into another patch of color."],
  ], snarky: [
    ["拼布披风的配色很自由，晚饭预算不行。", "Patchwork colors are flexible. Dinner budgets aren't."],
    ["虹彩负责气氛，我负责询问蛋糕几点来。", "The rainbow handles atmosphere. I ask when the cake arrives."],
    ["面纹很精致，吃饼干的姿势仍很朴素。", "Refined face paint. Very basic biscuit-eating technique."],
    ["庆典没有入场券，摸猫的排队倒挺认真。", "No party tickets. The head-pat queue is quite orderly."],
  ] },
  music: { gentle: [
    ["给每一次停顿，也留一个温柔的拍子。", "Leave a gentle beat for every pause too."],
    ["一段文字，一点鼓声，刚好陪过这一刻。", "A few words, a little drumming, company for this moment."],
    ["音符不用赶路，喜欢的旋律可以慢慢听。", "Notes needn't hurry. Enjoy a favorite tune slowly."],
    ["今天的合奏，也给安静留一个声部。", "Today's duet has a part for quiet too."],
  ], snarky: [
    ["猫咪的节拍器，是厨房开门的声音。", "My metronome is the sound of the kitchen door."],
    ["鼓点再复杂，开饭提示只要一声。", "Complex drum patterns. One dinner chime is enough."],
    ["我会即兴演奏，主要因为忘了上一拍。", "I improvise, mostly because I forgot the previous beat."],
    ["今日乐评：旋律不错，鱼干伴奏不足。", "Today's review: good melody, insufficient fish-treat accompaniment."],
  ] },
  lo: { gentle: [
    ["把罗的暖色摆好，让桌边多一点安心。", "Lo's warm color brings a little comfort to the desk."],
    ["小小的刻纹，也值得认真看一眼。", "Tiny markings deserve a thoughtful look too."],
    ["罗安静站着，我们慢慢把今天过好。", "Lo stands quietly while we take care of today."],
    ["喜欢的收藏，就让它留在看得见的地方。", "Keep a favorite collection where you can enjoy it."],
  ], snarky: [
    ["罗不怕加班，因为它的岗位是石头。", "Lo doesn't fear overtime. Its job is being a stone."],
    ["罗的刻痕很清楚，我的采购清单只有鱼。", "Clear markings on Lo. My shopping list only says fish."],
    ["符文石站得稳，猫咪听见开饭就不稳。", "The rune stands firm. Dinner announcements shake the cat."],
    ["罗看起来很沉，最重的还是我的起床决心。", "Lo looks heavy. My resolve to get up is harder to move."],
  ] },
  ber: { gentle: [
    ["贝的浅绿，像给桌边留一小片树荫。", "Ber's soft green feels like a little shade beside the desk."],
    ["把喜欢的贝摆好，今天也从小满足开始。", "Ber in place. Start today with a little contentment."],
    ["不必急着许下一个更大的愿望。", "No need to rush into a bigger wish."],
    ["收藏有自己的节奏，我们慢慢欣赏。", "Collections have their own pace. Enjoy them slowly."],
  ], snarky: [
    ["贝的职责是站岗，我的职责是检查餐桌。", "Ber guards the desk. I inspect the dinner table."],
    ["贝不会掉毛，保洁部门对它很满意。", "Ber sheds no fur. The cleaning department approves."],
    ["无限的想象，配上有限的零食预算。", "Infinite imagination, finite snack budget."],
    ["这块贝很安静，安静得不像有饭要催。", "Ber is suspiciously quiet for someone with dinner to request."],
  ] },
  jah: { gentle: [
    ["乔的银灰色，给今天留一点清亮。", "Jah's silver gray brings a little clarity to today."],
    ["把乔摆在身边，慢慢欣赏手里的小愿望。", "Jah beside us, a little wish to enjoy at our own pace."],
    ["石头静静陪着，旅途不需要每刻都热闹。", "A quiet stone. A journey needn't be lively every moment."],
    ["再远的愿望，也可以从桌边的一点喜欢开始。", "Even a distant wish can start with a small favorite on the desk."],
  ], snarky: [
    ["乔不会传送外卖，这份功能需求我记下了。", "Jah won't teleport takeout. Feature request noted."],
    ["乔已经很帅了，没必要再给它戴我的领结。", "Jah looks good already. It doesn't need my bow tie."],
    ["谜团今天的新题：开罐器到底去哪了。", "Today's Enigma: where did the can opener go?"],
    ["乔站得很端正，我坐得很有弹性。", "Jah stands properly. My sitting posture is more flexible."],
  ] },
  wings: { gentle: [
    ["羽翼轻轻展开，给今天多一点想象。", "Wings gently open for a little more imagination today."],
    ["有翅膀也不用赶路，慢慢陪你就很好。", "Wings don't mean we have to hurry. Company is enough."],
    ["软羽接住晨光，也接住一小点好心情。", "Soft feathers catch the dawn and a little good mood."],
    ["蝶翼像一封花园寄来的小信。", "Butterfly wings feel like a little letter from the garden."],
    ["小蝠翼把暮色折好，留在安静的桌边。", "Little bat wings fold the twilight beside a quiet desk."],
    ["冰羽很清亮，陪伴依然暖暖的。", "Clear frost feathers, warm little company."],
    ["发条飞翼装好了，把好奇心带到远一点的地方。", "Clockwork wings ready to carry curiosity a little farther."],
    ["星图沿着羽翼铺开，每个点都像小小的愿望。", "Stars across the wings, each like a little wish."],
    ["今天先把翅膀收好，给自己一个舒服的坐姿。", "Fold the wings today and find a comfortable seat."],
    ["远方可以慢慢看，眼前也有值得喜欢的风景。", "The horizon can wait. There's beauty right here too."],
    ["一对小翅膀，也能装下轻轻的勇气。", "Little wings can hold a little courage."],
    ["羽翼不是催促，是桌边的一点自由。", "These wings are a little freedom beside the desk."],
  ], snarky: [
    ["翅膀装备好了，飞行许可由饭碗部门审核。", "Wings equipped. Flight clearance comes from the food-bowl department."],
    ["软羽很轻，吃完饭的猫就另说了。", "Light feathers. The cat after dinner is another matter."],
    ["蝠翼很神秘，打哈欠时还是会暴露。", "Mysterious bat wings. A yawn still gives me away."],
    ["蝶翼的配色很丰富，我的脑袋里只有鱼。", "Colorful butterfly wings. A mind full of fish."],
    ["冰羽不用冷藏，罐头也请遵守这个原则。", "No refrigeration needed for frost wings. Please apply that to dinner."],
    ["发条飞翼不包电池，也不包自动上班。", "Clockwork wings include neither batteries nor automatic work attendance."],
    ["星图之翼很漂亮，飞去厨房仍然需要路线。", "Lovely constellation wings. Still need directions to the kitchen."],
    ["翅膀不加移速，催饭的气势倒是增加了。", "No speed bonus from these wings. Stronger dinner demands, though."],
    ["起飞前检查：羽毛齐全，零食不足。", "Preflight check: all feathers present, snacks insufficient."],
    ["披风加翅膀，转身前先确认茶杯位置。", "Cape plus wings: locate the teacup before turning."],
    ["飞行员帽戴得很稳，纸飞机还是飞反了。", "Aviator cap secure. Paper plane flew backwards."],
    ["我的航空公司只有一条航线：桌面到饭碗。", "My airline has one route: desktop to food bowl."],
  ] },
  aura: { gentle: [
    ["光环留在脚边，给平常的一刻添一点亮。", "An aura at my feet brightens an ordinary moment."],
    ["暖阳光环很柔和，适合陪你慢慢做事。", "A soft dawn aura for working at your own pace."],
    ["月晕轻轻铺开，把夜晚围得安静一点。", "A moon halo makes a little circle of nighttime calm."],
    ["绿意绕着桌边，像一小片留住的春天。", "A ring of green, a little spring saved beside the desk."],
    ["奥术的线条很小，想象可以很远。", "Tiny arcane lines, far-reaching imagination."],
    ["炉火的颜色，给工作留一个暖暖的结尾。", "Ember colors make a warm little ending to the workday."],
    ["虹彩圈住的，是每次重逢的小开心。", "A rainbow circle holds the joy of every return."],
    ["光环不用很耀眼，温柔的亮就足够。", "An aura needn't dazzle. A gentle light is enough."],
    ["把喜欢的颜色，留在今天的脚边。", "Keep a favorite color at your feet today."],
    ["一点光，一点陪伴，刚好够这一刻。", "A little light, a little company, enough for this moment."],
    ["圈外是忙碌，圈里留一点从容。", "A busy day outside, a little ease within the circle."],
    ["让柔光陪着鼓点，今天慢慢来。", "Let a soft glow share the beat. Take your time today."],
  ], snarky: [
    ["光环负责发光，我负责不想起床。", "The aura shines. I handle reluctance to get up."],
    ["暖阳光环不能烤鱼，这个需求很遗憾。", "The dawn aura won't grill fish. A disappointing limitation."],
    ["月晕很浪漫，夜宵需求很现实。", "Romantic moon halo, practical midnight-snack needs."],
    ["绿意光环不用浇水，也别顺手浇猫。", "No watering the leaf aura. Or the cat, while you're at it."],
    ["奥术光环看起来复杂，使用方法是坐着。", "Complex-looking arcane aura. Instructions: sit."],
    ["炉火光环只有氛围，没有取暖补贴。", "The ember aura supplies atmosphere, no heating allowance."],
    ["虹彩配好了，零食也该按颜色配齐。", "Rainbow equipped. Snacks should now come in matching colors."],
    ["别站进光环里催进度，猫咪只接收摸头。", "Standing in the aura won't speed things up. Head pats accepted."],
    ["光环不能清空仓库，这已经是第三次问了。", "The aura won't clear your stash. Third time asking."],
    ["这个圈不是充电座，猫咪续航靠饭。", "This ring isn't a charging dock. The cat runs on food."],
    ["桌面上有了魔法阵，文件还是要自己整理。", "A magic circle on the desk. Files still need manual sorting."],
    ["光环再亮，也照不出丢在桌下的笔。", "Even a bright aura won't find the pen under the desk."],
  ] },
};
