//! Retires only unmodified Tauri-generated permissions for removed commands.
//!
//! Tauri regenerates current commands, then reads every file in its generated
//! directory. It does not retire files for commands removed since the last build.
//! Match the complete standard template before deletion; a header alone is not
//! proof that a file remains generator-owned.
use std::{fs, io, path::Path};

fn standard_permission(command: &str) -> String {
    let identifier = command.replace('_', "-");
    format!(
        "# Automatically generated - DO NOT EDIT!\n\n\
[[permission]]\n\
identifier = \"allow-{identifier}\"\n\
description = \"Enables the {command} command without any pre-configured scope.\"\n\
commands.allow = [\"{command}\"]\n\n\
[[permission]]\n\
identifier = \"deny-{identifier}\"\n\
description = \"Denies the {command} command without any pre-configured scope.\"\n\
commands.deny = [\"{command}\"]\n"
    )
}

fn is_link(metadata: &fs::Metadata) -> bool {
    if metadata.file_type().is_symlink() {
        return true;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        metadata.file_attributes() & 0x400 != 0
    }
    #[cfg(not(windows))]
    false
}

fn ordinary_directory(path: &Path) -> io::Result<bool> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() && !is_link(&metadata) => Ok(true),
        Ok(_) => Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            format!(
                "refusing generated-permission cleanup through a non-ordinary directory: {}",
                path.display()
            ),
        )),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(error),
    }
}

pub fn retire_removed_commands(manifest_dir: &Path, commands: &[&str]) -> io::Result<Vec<String>> {
    let root = fs::canonicalize(manifest_dir)?;
    let permissions = root.join("permissions");
    if !ordinary_directory(&permissions)? {
        return Ok(Vec::new());
    }
    let permissions = fs::canonicalize(&permissions)?;
    if permissions.parent() != Some(root.as_path()) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "permissions escaped their directory",
        ));
    }
    let generated = permissions.join("autogenerated");
    if !ordinary_directory(&generated)? {
        return Ok(Vec::new());
    }
    let generated = fs::canonicalize(&generated)?;
    if generated.parent() != Some(permissions.as_path()) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "generated permissions escaped their directory",
        ));
    }
    let mut retired = Vec::new();
    // Only direct children belong to AppManifest::commands. Never recurse or
    // examine custom permissions in the parent directory.
    for entry in fs::read_dir(&generated)? {
        let path = entry?.path();
        let metadata = fs::symlink_metadata(&path)?;
        if !metadata.is_file()
            || is_link(&metadata)
            || metadata.len() > 8192
            || path.extension().and_then(|extension| extension.to_str()) != Some("toml")
        {
            continue;
        }
        let Some(command) = path.file_stem().and_then(|name| name.to_str()) else {
            continue;
        };
        if command.is_empty()
            || !command
                .bytes()
                .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
            || commands.contains(&command)
        {
            continue;
        }
        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(error) if error.kind() == io::ErrorKind::InvalidData => continue,
            Err(error) => return Err(error),
        };
        if contents.replace("\r\n", "\n") == standard_permission(command) {
            fs::remove_file(&path)?;
            retired.push(command.to_string());
        }
    }
    retired.sort();
    Ok(retired)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicUsize, Ordering};
    static NEXT_FIXTURE: AtomicUsize = AtomicUsize::new(0);

    // Frozen from tauri-utils::acl::build's application command template
    // (empty license header, schema_ref=false), independently of our matcher.
    const STANDARD: &str = "# Automatically generated - DO NOT EDIT!\n\n\
[[permission]]\n\
identifier = \"allow-obsolete-command\"\n\
description = \"Enables the obsolete_command command without any pre-configured scope.\"\n\
commands.allow = [\"obsolete_command\"]\n\n\
[[permission]]\n\
identifier = \"deny-obsolete-command\"\n\
description = \"Denies the obsolete_command command without any pre-configured scope.\"\n\
commands.deny = [\"obsolete_command\"]\n";

    struct Fixture(PathBuf);
    impl Fixture {
        fn new() -> Self {
            let id = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let path = std::env::temp_dir().join(format!(
                "hub-generated-permissions-{}-{id}-{}",
                std::process::id(),
                NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir(&path).unwrap();
            fs::create_dir_all(path.join("permissions/autogenerated")).unwrap();
            Self(path)
        }
        fn generated(&self, name: &str) -> PathBuf {
            let directory = self.0.join("permissions/autogenerated");
            if name.is_empty() {
                directory
            } else {
                directory.join(name)
            }
        }
    }
    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn only_retired_standard_files_are_removed_and_cleanup_is_idempotent() {
        let fixture = Fixture::new();
        let stale = fixture.generated("obsolete_command.toml");
        fs::write(&stale, STANDARD.replace('\n', "\r\n")).unwrap();
        let current = fixture.generated("current_command.toml");
        fs::write(&current, STANDARD.replace("obsolete", "current")).unwrap();
        let custom = fixture.0.join("permissions/custom.toml");
        fs::write(&custom, STANDARD).unwrap();
        let nested = fixture.generated("custom/obsolete_command.toml");
        fs::create_dir(nested.parent().unwrap()).unwrap();
        fs::write(&nested, STANDARD).unwrap();

        assert_eq!(
            retire_removed_commands(&fixture.0, &["current_command"]).unwrap(),
            ["obsolete_command"]
        );
        assert!(!stale.exists());
        assert_eq!(
            fs::read_to_string(current).unwrap(),
            STANDARD.replace("obsolete", "current")
        );
        assert_eq!(fs::read_to_string(custom).unwrap(), STANDARD);
        assert_eq!(fs::read_to_string(nested).unwrap(), STANDARD);
        assert!(retire_removed_commands(&fixture.0, &["current_command"])
            .unwrap()
            .is_empty());
    }

    #[test]
    fn customized_headered_files_and_filename_mismatches_remain_untouched() {
        let fixture = Fixture::new();
        let examples = [
            (
                "obsolete_command.toml",
                format!("{STANDARD}\n# user customization\n"),
            ),
            ("another_command.toml", STANDARD.to_string()),
            (
                "manual.toml",
                "[[permission]]\nidentifier = \"manual\"\n".to_string(),
            ),
            (
                "extra_scope.toml",
                STANDARD.replace("obsolete_command", "extra_scope").replace(
                    "commands.allow = [\"extra_scope\"]",
                    "commands.allow = [\"extra_scope\", \"other\"]",
                ),
            ),
        ];
        for (name, contents) in &examples {
            fs::write(fixture.generated(name), contents).unwrap();
        }
        assert!(retire_removed_commands(&fixture.0, &[]).unwrap().is_empty());
        for (name, contents) in examples {
            assert_eq!(
                fs::read_to_string(fixture.generated(name)).unwrap(),
                contents
            );
        }
    }

    #[test]
    fn missing_generated_directory_is_a_clean_first_build() {
        let fixture = Fixture::new();
        fs::remove_dir(fixture.generated("")).unwrap();
        assert!(retire_removed_commands(&fixture.0, &[]).unwrap().is_empty());
    }

    #[test]
    fn non_directory_generated_path_fails_without_touching_custom_permissions() {
        let fixture = Fixture::new();
        let generated = fixture.generated("");
        fs::remove_dir(&generated).unwrap();
        fs::write(&generated, STANDARD).unwrap();
        assert!(retire_removed_commands(&fixture.0, &[]).is_err());
        assert_eq!(fs::read_to_string(generated).unwrap(), STANDARD);
    }

    #[cfg(unix)]
    #[test]
    fn linked_generated_directory_is_never_followed() {
        let fixture = Fixture::new();
        let generated = fixture.generated("");
        fs::remove_dir(&generated).unwrap();
        let outside = fixture.0.join("outside");
        fs::create_dir(&outside).unwrap();
        fs::write(outside.join("obsolete_command.toml"), STANDARD).unwrap();
        std::os::unix::fs::symlink(&outside, &generated).unwrap();
        assert!(retire_removed_commands(&fixture.0, &[]).is_err());
        assert_eq!(
            fs::read_to_string(outside.join("obsolete_command.toml")).unwrap(),
            STANDARD
        );
    }
}
